- hosts: osm.towiski.de
  remote_user: ansible
  become: yes
  become_user: root
  #gather_facts: no
  roles:
    #- vminstaller
    #- linux
    - osm
  vars:
    ansible_port: 22
    hyper: hv2.towiski.de
    distro: ubuntu1804
    machinearch: x86_64
    vmwaittime: 20
    virtualcpus: 6
    ramsize: 32768
    sshdrsakeylength: 4096
    sshdecdsakeylength: 521
    language: en_US
    locale: en_US.utf8
    keyboard: us
    timezone: Europe/Berlin
    nics:
      #- { type: bridge , name: brpub , device: eth0 , model: virtio-net , onboot: yes , bootproto: static , ip: '2a01:4f9:2b:2921:7::2' , netmask: 'ffff:ffff:ffff:ffff::' , gateway: 'fe80::1' , nameserver: '2a01:4f8:0:1::add:9999' , mac: '00:50:56:00:0B:CB' }
      - { type: bridge , name: brpub , device: eth0 , model: virtio-net , onboot: yes , bootproto: static , ip: '95.216.246.231' , netmask: '255.255.255.192' , gateway: '95.216.246.193' , nameserver: '213.133.98.98' , mac: '00:50:56:00:0B:CB' }
      - { type: bridge , name: brint , device: eth1 , model: virtio-net , onboot: yes , bootproto: dhcp , gateway: 'fd5d:3644:b0fe::1' , nameserver: 'fd5d:3644:b0fe::1' }
    preseednic: eth0
    iscsinic: ''
    hostname: osm
    domainname: towiski.de
    virtualfilespath: 
    disks:
      - { name: vda , pool: virtimages , size: 200G }
      - { name: vdb , device: /dev/md127 , bootorder: 1000, size: 0G }
    partitions: 
      - "100000 300001 300000 ext4 $primary{ } $bootable{ } method{ format } format{ } use_filesystem{ } filesystem{ ext4 } mountpoint{ / } ."
      - "2048 2050 2148 linux-swap $primary{ } method{ swap } format{ } ."
    bootpartition: vda
    sshpubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    gis_dbname: gis
    osm_username: osm
    website: "{{ ansible_host }}"
    styles:
      - name: carto-de
        #version: 'v4.23.0'
        #version: 'v4.23.0-split'
        default_language: en
        test: yes
      - name: carto
        version: 'v4.23.0'
    download_planet: no
    download_regions: [ asia/laos , asia/sri-lanka ]
    planet_url: 'https://download.bbbike.org/osm/planet/planet-latest.osm.pbf'
    use_postgresql_11: no
    psql_tuning:
      shared_buffers: 8GB
      checkpoint_timeout: 1h
      checkpoint_completion_target: 0.8
      checkpoint_flush_after: 256
      effective_cache_size: 12GB
      maintenance_work_mem: 2GB
      work_mem: 128MB
      wal_buffers: 16MB
      random_page_cost: 1.1
      effective_io_concurrency: 200
      max_worker_processes: 6
      max_parallel_workers_per_gather: 3
      max_parallel_workers: 6
      default_statistics_target: 500
      fsync: off
      autovacuum: on
      autovacuum_max_workers: 1
      autovacuum_naptime: 30min
    renderd_tuning:
      threads: 4
      tiledir: /var/lib/mod_tile
