- hosts: $MY_TILE_SERVER
  remote_user: ansible
  become: yes
  become_user: root
  gather_facts: no
  roles:
    - vminstaller
    - linux
    - osm
  vars:
    ansible_port: 22
    hyper: $MY_HYPERVISOR
    distro: ubuntu1804
    machinearch: x86_64
    vmwaittime: 20
    virtualcpus: 6
    ramsize: 49152
    sshdrsakeylength: 4096
    sshdecdsakeylength: 521
    language: en_US
    locale: en_US.utf8
    keyboard: us
    timezone: Europe/Berlin
    nics:
      - name: brpub
        ip: '$MY_IP'
        netmask: '$MY_NETMASK'
        gateway: '$MY_GATEWAY'
        nameserver: '$MY_NAMESERVER'
        mac: '$MY_MAC'
        type: bridge
        device: eth0
        model: virtio-net
        onboot: yes
        bootproto: static
    preseednic: eth0
    iscsinic: ''
    hostname: $MY_HOSTNAME
    domainname: $MY_DOMAIN
    virtualfilespath: 
    disks:
      - { name: vda , pool: virtimages , size: 200G }
      - { name: vdb , device: /dev/md127 , bootorder: 1000, size: 0G }
    partitions: 
      - "100000 300001 300000 ext4 $primary{ } $bootable{ } method{ format } format{ } use_filesystem{ } filesystem{ ext4 } mountpoint{ / } ."
      - "2048 2050 2148 linux-swap $primary{ } method{ swap } format{ } ."
    bootpartition: vda
    sshpubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    gis_dbname: gis
    osm_username: osm
    osm_psql_password: preferablyalongandrandompassword
    website: "{{ ansible_host }}"
    styles:
      - name: carto-de
        #version: 'v4.23.0-split' -- currently broken, just use HEAD
        default_language: en
      - name: carto
        version: 'v4.23.0'
    download_planet: no
    download_regions: [ asia/laos , asia/sri-lanka ]
    planet_url: 'https://download.bbbike.org/osm/planet/planet-latest.osm.pbf'
    use_postgresql_11: no
    psql_tuning:
      shared_buffers: 12GB
      checkpoint_timeout: 1h
      checkpoint_completion_target: 0.8
      checkpoint_flush_after: 256
      effective_cache_size: 24GB
      maintenance_work_mem: 2GB
      work_mem: 128MB
      wal_buffers: 16MB
      random_page_cost: 1.1
      effective_io_concurrency: 200
      max_worker_processes: 6
      max_parallel_workers_per_gather: 3
      max_parallel_workers: 6
      default_statistics_target: 500
      fsync: off
      autovacuum: on
      autovacuum_max_workers: 1
      autovacuum_naptime: 30min
    renderd_tuning:
      threads: 6
      tiledir: /var/lib/mod_tile
