- name: install carto via NPM (ugh :-S)
  shell: "npm -g install carto"
  args:
    creates: /usr/local/bin/carto

- name: make mapnik dir
  file:
    dest: /etc/mapnik-osm-data
    state: directory
    mode: '755'

- include: "style_{{ style.name }}.yaml"
  with_items: "{{ styles }}"
  loop_control:
    loop_var: style

- name: patch style.mml with database credentials
  shell: "cd /etc/mapnik-osm-data/carto && mv project.mml project.mml.orig && perl -MYAML::XS=LoadFile,DumpFile -e'$d=LoadFile(q(project.mml.orig));@{$d->{_parts}{osm2pgsql}}{qw(host dbname user password)}=@ARGV;DumpFile(q(project.mml),$d)' localhost {{ gis_dbname }} {{ osm_username }} {{ db_password }}"

- name: compile style.xml and test
  shell: "cd /etc/mapnik-osm-data/carto && make"
  args:
    creates: "/etc/mapnik-osm-data/carto/style.xml"
