- name: install carto via NPM (ugh :-S)
  shell: "npm -g install carto"
  args:
    creates: /usr/local/bin/carto

- name: make mapnik dir
  file:
    dest: /etc/mapnik-osm-data
    state: directory
    mode: '755'

- name: make post-import dir
  file:
    dest: ~/post-import.d
    state: directory
    mode: '755'
  become: yes
  become_user: "{{ osm_username }}"

- include: "style_{{ style.name }}.yaml"
  with_items: "{{ styles }}"
  loop_control:
    loop_var: style
