- name: create random database password
  local_action: command pwgen 20 1
  become: no
  register: random_password
  when: not osm_psql_password

- debug: msg="Generated random password for PostgreSQL osm user '{{ random_password.stdout }}'"
  when: not osm_psql_password

- set_fact: osm_psql_password={{ random_password.stdout }}
  when: not osm_psql_password

- include: software.yaml
- include: user.yaml
- include: postgres.yaml
- include: apache.yaml
  vars:
    webroot: "/var/www/{{ website }}"
    webadmin: "webmaster@{{ domainname }}"
- include: renderd.yaml
- include: carto.yaml
- include: data.yaml
