- include: renderd_section.yaml
  vars:
    section: renderd
    params:
      stats_file: /var/run/renderd/renderd.stats
      socketname: /var/run/renderd/renderd.sock
      tile_dir: /var/lib/mod_tile
      num_threads: "{{ renderd_tuning.threads }}"

- include: renderd_section.yaml
  vars:
    section: mapnik
    params:
      plugins_dir: /usr/lib/mapnik/3.0/input
      font_dir: /usr/share/fonts/truetype/
      font_dir_recurse: true

- name: remove renderd default section
  ini_file:
    path: /etc/renderd.conf
    section: default
    state: absent
  notify: restart_renderd
