- name: configure renderd {{ section }} params
  ini_file:
    path: /etc/renderd.conf
    section: "{{ section }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    mode: '0644'
    backup: no
    no_extra_spaces: yes
  loop: "{{ params | dict2items }}"
  notify: restart_renderd
