- name: install extra packages for carto-de
  apt:
    install_recommends: no
    update_cache: no
    name: "{{ packages }}"
  vars:
    packages:
    - postgresql-10-osml10n
    - fonts-noto-cjk
    - fonts-noto-hinted
    - fonts-noto-unhinted
    - fonts-hanazono

- name: add carto-de specific PostgreSQL extension
  become: yes
  become_user: postgres
  postgresql_ext: db={{ gis_dbname }} cascade=yes name=osml10n

- name: check out carto-de repo
  git:
    repo: 'https://github.com/giggls/openstreetmap-carto-de.git'
    dest: /etc/mapnik-osm-data/{{ style.name }}
    force: yes
    # version: "{{ style.version }}" currently broken, use HEAD

- name: download shapefiles
  shell: 'cd /etc/mapnik-osm-data/{{ style.name }} && scripts/get-shapefiles.py'
  args:
    creates: "/etc/mapnik-osm-data/{{ style.name }}/data/antarctica-icesheet-outlines-*/icesheet_outlines.shp"

# Workaround for shape files unavailable from upstream
# see https://github.com/giggls/openstreetmap-carto-de/issues/41
- include: download_unpack_shapefile.yaml
  with_items: [ lakes , ocean , river ]
  loop_control:
    loop_var: shape_file
  vars:
    shapefile: "{{ shape_file }}"

- name: create post-import view setup script
  template:
    src: postimport-carto_de.sh
    dest: ~/post-import.d/carto-de.sh
    mode: '755'
  become: yes
  become_user: "{{ osm_username }}"

- name: patch style.mml with database credentials
  shell: "cd /etc/mapnik-osm-data/{{ style.name }} && mv project.mml project.mml.orig && perl -MYAML::XS=LoadFile,DumpFile -e'$d=LoadFile(q(project.mml.orig));@{$d->{_parts}{osm2pgsql}}{qw(host dbname user password)}=@ARGV;DumpFile(q(project.mml),$d)' localhost {{ gis_dbname }} {{ osm_username }} {{ db_password }}"

- name: compile style.xml
  shell: "cd /etc/mapnik-osm-data/{{ style.name }} && make"
  args:
    creates: "/etc/mapnik-osm-data/{{ style.name }}/style.xml"

- include: renderd_style_section.yaml style_xml=osm-de.xml
